### ISSUE TITLE
problems with the DLL max issue

### ISSUE THREAD

**Issue by oeco28** [bvieth/powsimR#1]
Hello Beate,
  I am trying to install powsimR and I am running into the max loaded DLL issues that you mentioned. If I restart R after installing dependencies, and I look at the number of DLL loaded  >length(getLoadedDLLs())
12
there are only 12. I even unload stats and tools:
dyn.unload("/Library/Frameworks/R.framework/Versions/3.4/Resources/library/stats/libs/stats.so")
dyn.unload("/Library/Frameworks/R.framework/Versions/3.4/Resources/library/tools/libs/tools.so")

but I still get the same problem:
devtools::install_github("bvieth/powsimR")
Downloading GitHub repo bvieth/powsimR@master
from URL https://api.github.com/repos/bvieth/powsimR/zipball/master
Installing powsimR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/tw/kcbwlvs56ys_x3xnslrmfhrr0000gn/T/Rtmp4QyPQa/devtools1304d1c481da6/bvieth-powsimR-876dd55'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘powsimR’ ...
** R
** preparing package for lazy loading

 For updates of the NBGOF package, please visit https://github.com/gu-mi/NBGOF 

Error : .onLoad failed in loadNamespace() for 'mnormt', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/mnormt/libs/mnormt.so':
  `maximal number of DLLs reached...
ERROR: lazy loading failed for package ‘powsimR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/powsimR’
Installation failed: Command failed (1)

how many dependencies is powsimR loading? Do you have any additional recommendations?

thank you!
Omar

**Comment by bvieth** [comment]
Dear Omar,

thank you for trying out powsimR :)

I am assuming you are using a MAC based on your library path structure.

Starting with R 3.4, you can change the number of DLLs to a higher number. To do so, you first need to locate your Renviron file where the environmental variables are defined ( this file is called for Sys.getenv() in R for example). On my Ubuntu machine this file is in R_HOME/etc/ where R_HOME is /usr/lib/R. On a Mac it can be in /Library/Frameworks/R.framework/Versions/3.4/Resources/etc/. In that file add the following line R_MAX_NUM_DLLS=153. Then restart your R and check the output of Sys.getenv("R_MAX_NUM_DLLS"). 
After that, installation should be possible without an error.

I hope this helps and please contact me if you encounter any error / have questions.

Best
Beate

**Comment by swvanderlaan** [comment]
Awesome instructions @bvieth, but how do you get to the number "153"?

**Comment by bvieth** [comment]
Dear Sander,

that number was the highest I could set without issue on the MAC of my colleague. It is an older machine, so I guess a higher number is possible on newer machines but actually not needed for powsimR installation.

Kind regards
Beate

**Comment by swvanderlaan** [comment]
Excellent. Thank you for the information @bvieth.
