### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by del2007** [bvieth/powsimR#12]
Hi, would you kindly help me sort out this install error? Thanks!

Downloading GitHub repo bvieth/powsimR@master
from URL https://api.github.com/repos/bvieth/powsimR/zipball/master
Installing powsimR
svn: E170013: Unable to connect to a repository at URL 'https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/S4Vectors'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted
Installation failed: There was a problem retrieving the current SVN revision
Warning message:
running command ''/usr/bin/svn' info --xml --username readonly --password readonly https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/S4Vectors' had status 1

**Comment by bvieth** [comment]
Hi,

Thank you for trying out powsimR! I am sorry to see that you have issues installing it. 

This appears to be a Bioconductor related error. I would first try to update/upgrade your [biocLite](https://www.bioconductor.org/install/) / biocInstaller and then continue with the manual installation of powsimR dependencies (see [README](https://github.com/bvieth/powsimR/blob/master/README.md)).

HTH
Beate
