### ISSUE TITLE
Installing on macOS

### ISSUE THREAD

**Issue by swvanderlaan** [bvieth/powsimR#13]
Hi,

Maybe this is not really an issue, rather a bug?

I've installed `R` via `home-brew`. And now I wanted to install the `powsimR` package. All in all, not an issue (on R-3.4.2), except for the PDF creation of the vignettes. Apparently one needs LaTeX for that. So to make it work I did this:

#### step 1
I made sure `home-brew` is up-to-date.

#### step 2
I installed a basic LaTeX package; following these instructions: [https://tex.stackexchange.com/a/319572](https://tex.stackexchange.com/a/319572).

`brew cask install basictex`

#### step 3
I rebooted.

#### step 4
I updated `tlmgr` and after that install `titling` as root

```
sudo tlmgr update --self
sudo tlmgr install titling
```

#### step 5
It's recommended to also install the recommended font-collection.

`sudo tlmgr install collection-fontsrecommended`

#### step 6
I try to install `powsimR`:

`devtools::install_github('bvieth/powsimR', build_vignettes = TRUE,  dependencies = FALSE)`

But now I get this message:

```
devtools::install_github('bvieth/powsimR', build_vignettes = TRUE, dependencies = FALSE)
Downloading GitHub repo bvieth/powsimR@master
from URL https://api.github.com/repos/bvieth/powsimR/zipball/master
Installing powsimR
'/usr/local/Cellar/r/3.4.3_1/lib/R/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build  \
  '/private/var/folders/kh/0s66cjl5487fg_fhwgxqd2340000gn/T/RtmpIQ11b5/devtools5b223199244/bvieth-powsimR-0e31927'  \
  --no-resave-data --no-manual

* checking for file ‘/private/var/folders/kh/0s66cjl5487fg_fhwgxqd2340000gn/T/RtmpIQ11b5/devtools5b223199244/bvieth-powsimR-0e31927/DESCRIPTION’ ... OK
* preparing ‘powsimR’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Warning: running command 'kpsewhich framed.sty' had status 1
Warning in test_latex_pkg("framed", system.file("misc", "framed.sty", package = "knitr")) :
  unable to find LaTeX package 'framed'; will use a copy from knitr
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  Running 'texi2dvi' on 'powsimR.tex' failed.
LaTeX errors:
! LaTeX Error: File `beramono.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
Calls: <Anonymous> -> texi2pdf -> texi2dvi
Execution halted
Installation failed: Command failed (1)
```

Hope you have a solution? I know, building the vignettes is not strictly needed...nonetheless... :-)

Best,

Sander

**Comment by cziegenhain** [comment]
Hey Sander,

I'm using powsimR on my Mac but haven't tried building vignettes myself.
It seems your basic Latex installation doesn't contain the right packages.
Maybe you should give [MacTex](http://www.tug.org/mactex/) a go, as far as I know thats a pretty comprehensive Latex distribution.

Good luck,

Christoph
