### ISSUE TITLE
problem with evaluateDist function

### ISSUE THREAD

**Issue by yoshiuva** [bvieth/powsimR#14]
Dear Beate,

Could you give me the instruction to fix the following error?
I tried your powsimR example code from the vignette. And when I was running the function evaluateDist, I got an error message. I am using R version 3.4.3 and Bioconductor version 3.6.

> evaluateDist(cnts = kolodziejczk_cnts, RNAseq = "singlecell",
+              ncores = 1, nsims = 1, frac.genes = 1, min.meancount = 1,
+              min.libsize = 1000)

Error in evaluateDist(cnts = kolodziejczk_cnts, RNAseq = "singlecell",  : 
  could not find function "evaluateDist"

Thank you,

Yoshi

**Comment by bvieth** [comment]
Dear Yoshi,

for some time I excluded that function due to maintenance. Now it should be available again.

Kind regards
Beate
