### ISSUE TITLE
simulateDE() is missing example options for the normalisation argument 

### ISSUE THREAD

**Issue by gleparc** [bvieth/powsimR#16]
Dear Author,

Thank you for developing this very useful tool.

I just wanted to leave you a note, I was looking at the simulateDE function with ?simulateDE and notice that the possibilities for the argument "normalisation" are missing in the documentation e.g.:

>?simulateDE

Simulate Differential Expression
<...snip...>
Normalisation method to use. Available options are:

So far in your example code you use normalisation = "scran", perhaps you intended to have others as well? eg. TMM ?  ( i just tried that now and it works with TMM)

Thanks again!

**Comment by bvieth** [comment]
Hello, 

thank you very much for pointing that out. I hope that this is fixed now in the newest release, where I have added some extra functionalities to simulateDE as well.

Kind regards
Beate
