### ISSUE TITLE
Installation failed: SVN does not seem to be installed on your system.

### ISSUE THREAD

**Issue by wpappa** [bvieth/powsimR#18]
Hello, 

I am trying to install powsimR. I follow the instructions but I keep getting the following error message:
 
Installation failed: SVN does not seem to be installed on your system.

 I am not sure why  do I need an SVN system and which version do I need.

Thank you

**Comment by bvieth** [comment]
Hello,

the svn system is used by bioconductor.

On my ubuntu machine, I used `sudo apt-get install subversion libapache2-svn` to install it.

I recommend that you first install the dependencies of powsimR and then powsimR itself, either by using devtools or by downloading a source code version and using `install.packages()`.

I hope this helps and feel free to message me if you need any further assistance.

Kind regards
Beate

**Comment by wpappa** [comment]
Hi Beate,

Thank you for the response.
However,  I am working through RStudio on Windows. Do you have any instructions for this set up?
I am not sure if it makes any difference, but I do have Git installed on my computer. I am not sure if there is something additional I should be doing though as I still get the same error message.

Best Regards,
Vasso

**Comment by bvieth** [comment]
Dear Vasso,

svn is needed for the automatic installation of powsimR dependencies by using the Remotes entries in the DESCRIPTION file. Were you able to install the dependencies manually and then subsequently install powsimR with `devtools::install_github("bvieth/powsimR", build_vignettes = TRUE, dependencies = FALSE)` ?
Unfortunately, some of the dependencies in powsimR (particular implementation for parallel computation) used to be (might have changed) not available for Windows.
If you could run the following (i.e. try to install the dependencies of powsimR) and record the packages that are not available for your system, I can make a version without these and make it available as a source package for download.

```{r}
ipak <- function(pkg, repository = c("CRAN", "Bioconductor", "github")) {
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    # new.pkg <- pkg
    if (length(new.pkg)) {
        if (repository == "CRAN") {
            install.packages(new.pkg, dependencies = TRUE)
        }
        if (repository == "Bioconductor") {
            source("https://bioconductor.org/biocLite.R")
            biocLite(new.pkg, dependencies = TRUE, ask = FALSE)
        }
        if (repository == "github") {
            devtools::install_github(new.pkg, build_vignettes = FALSE, dependencies = TRUE)
        }
    }
}

# CRAN PACKAGES
cranpackages <- c("bbmle", "broom", "cluster", "cobs", "cowplot", "data.table",
    "doParallel", "dplyr", "drc", "DrImpute", "fastICA", "fitdistrplus", "foreach", 
    "gamlss.dist", "ggExtra", "ggplot2", "ggthemes", "grDevices", "glmnet", 
    "grid", "gtools", "Hmisc", "kernlab", "MASS", "matrixStats", "mclust", "methods", 
    "minpack.lm", "moments", "msir", "NBPSeq", "nonnest2", "parallel", "penalized", 
    "plyr", "pscl", "reshape2", "ROCR", "Rtsne", "scales", "Seurat", "snow", 
    "stats", "tibble", "tidyr", "VGAM", "ZIM")
ipak(cranpackages, repository = "CRAN")

# BIOCONDUCTOR
biocpackages <- c("AnnotationDbi", "baySeq", "Biobase", "BiocGenerics", "BiocParallel", 
    "DEDS", "DESeq2", "EBSeq", "edgeR", "IHW", "iCOBRA", "limma", "Linnorm", 
    "MAST", "monocle", "NOISeq", "qvalue", "ROTS", "RUVSeq", "S4Vectors", "scater", 
    "scDD", "scde", "scone", "scran", "SCnorm", "SingleCellExperiment", "SummarizedExperiment", 
    "zinbwave")
ipak(biocpackages, repository = "Bioconductor")

# GITHUB
githubpackages <- c("nghiavtr/BPSC", "VCCRI/cidr", "cz-ye/DECENT", "mohuangx/SAVER", 
    "statOmics/zingeR")
ipak(githubpackages, repository = "github")
```

I am assuming you are using R 3.4.4?

Kind regards
Beate

**Comment by bvieth** [comment]
Dear Vasso,

I will close the issue for now. Feel free to reopen if my suggestions did not help.

Kind regards
Beate
