### ISSUE TITLE
Max DLL issue revisited

### ISSUE THREAD

**Issue by mjdufort** [bvieth/powsimR#19]
I'm attempting to install powsimR on a Mac, and hitting the DLL limit even after setting it to the maximum number possible (153).

Here's the error message:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/nloptr/libs/nloptr.so':
  `maximal number of DLLs reached...
ERROR: lazy loading failed for package ‘powsimR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/powsimR’
Installation failed: Command failed (1)

And here's the sessionInfo() output:

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.18

**Comment by bvieth** [comment]
Hello,

starting with the new version I included an additional number of R packages for imputation and normalisation. Therefore I have changed the recommendations (see "DLLs and ulimit" in the README):

I recommend to increase the maximum number of DLLs that can be loaded to at least 500.
In addition, the user limits for open files (unix: ulimit) might have to be set to a higher number to accomodate the increase in DLLs. Please check out this help page for MACs: https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c.

Kind regards
Beate

**Comment by bvieth** [comment]
Hello,

I will close the issue. Feel free to reopen if my suggestions did not solve the issue for you.

Kind regards
Beate
