### ISSUE TITLE
Error building vignette

### ISSUE THREAD

**Issue by haniap** [bvieth/powsimR#2]
Hi Beate,
Installing powsimR using devtools::install_github("bvieth/powsimR", build_vignettes = TRUE) results in an error due to its inability to build the vignette. This is rectified if build_vignettes=FALSE, however I can't seem to find a complete vignette for powsimR (at least not on your github account or through the package). It would be great to have access to this.
Best,
Hania

**Comment by bvieth** [comment]
Dear Hania,

I am sorry to hear that the vignette knitting was unsuccesful. I hope I fixed the error now. there is also a copy available on github (https://github.com/bvieth/powsimR/tree/master/vignettes/powsimR.pdf)

Best
Beate

**Comment by haniap** [comment]
Dear Beate,
Thank you for that - I found that the first 5 pages were not knitting properly on github, but once downloaded it was all there. Thanks for looking into this.
Best,
Hania
