### ISSUE TITLE
issue similar to the one Vivianstats posted

### ISSUE THREAD

**Issue by abrantesas** [bvieth/powsimR#21]
Hello!
I got your package to install on an older computer a couple months ago but it was too slow to do any simulations.

I have since tried to install powsimR on a computing cluster and a newer computer and have had many issues. 

I get this problem on both installs. It seems to be related to the problem Vivianstats posted a few days back. Any ideas about what I should do?

Thanks so much!

 sim1.params <- estimateParam(countData=cnts,
                                batchData = NULL,
                                 spikeData = NULL,
                                 spikeInfo = NULL,
                                 Lengths = NULL,
                                 MeanFragLengths = NULL,
                                Distribution = 'NB',
                                RNAseq = 'singlecell',
                                normalisation = 'scran',
                                sigma = 1.96,
                                 NCores = NULL)
Error in scater::calculateQCMetrics(sce, nmads = 3) : 
  unused argument (nmads = 3)
> sessionInfo()

**Comment by bvieth** [comment]
Hello,

thank you for trying out powsimR!

scater changed its parameters for QC quality metrics. I have adapted my function call accordingly in the newest version (1.1.2). Feel free to give it another go and please tell me if you encounter other issues.

Kind regards
Beate

**Comment by abrantesas** [comment]
Great it works now! Although I think powsimR no longer loads the scater package. 
I get this error when running the simulateDE function: 

Applying MAST for DE analysis on raw count data.
Error in assayNames(x) : could not find function "assayNames"

If I load library(scater) it works fine.
Thanks again. Feel free to close the issue.

Shawn
