### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by gcrynen** [bvieth/powsimR#24]
Hi,
I have been trying to install powsimR however i am having some issues, i have read a few of the closed posts from other users and your advice but none of them helped thus far. I am using a windows machine with Rstudio and R version 3.4.4. version 3.5 doesnt work , apparently there is no version of Rtools currently available for R 3.5 or at least that is the error message i am getting. so i moved back to R 3.4.4. then I did exactly what was suggested but I am still having trouble.
any input will be greatly appreciated.
here is the log:

> ipak <- function(pkg, repository = c("CRAN", "Bioconductor", "github")) {
+     new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
+     # new.pkg <- pkg
+     if (length(new.pkg)) {
+         if (repository == "CRAN") {
+             install.packages(new.pkg, dependencies = TRUE)
+         }
+         if (repository == "Bioconductor") {
+             source("https://bioconductor.org/biocLite.R")
+             biocLite(new.pkg, dependencies = TRUE, ask = FALSE)
+         }
+         if (repository == "github") {
+             devtools::install_github(new.pkg, build_vignettes = FALSE, dependencies = TRUE)
+         }
+     }
+ }
> 
> # CRAN PACKAGES
> cranpackages <- c("bbmle", "broom", "cobs", "cowplot", "data.table", "devtools", 
+                   "doParallel", "dplyr", "drc", "DrImpute", "fastICA", "fitdistrplus", "foreach", 
+                   "gamlss.dist", "ggExtra", "ggplot2", "ggthemes", "grDevices", "glmnet", 
+                   "grid", "gtools", "Hmisc", "kernlab", "MASS", "matrixStats", "mclust", "methods", 
+                   "minpack.lm", "moments", "msir", "NBPSeq", "nonnest2", "parallel", "penalized", 
+                   "plyr", "pscl", "reshape2", "ROCR", "Rtsne", "scales", "Seurat", "snow", 
+                   "stats", "tibble", "tidyr", "VGAM", "ZIM")
> ipak(cranpackages, repository = "CRAN")
> 
> # BIOCONDUCTOR
> biocpackages <- c("AnnotationDbi", "baySeq", "Biobase", "BiocGenerics", "BiocParallel", 
+                   "DEDS", "DESeq2", "EBSeq", "edgeR", "IHW", "iCOBRA", "limma", "Linnorm", 
+                   "MAST", "monocle", "NOISeq", "qvalue", "ROTS", "RUVSeq", "S4Vectors", "scater", 
+                   "scDD", "scde", "scone", "scran", "SCnorm", "SingleCellExperiment", "SummarizedExperiment", 
+                   "zinbwave")
> ipak(biocpackages, repository = "Bioconductor")
> 
> # GITHUB
> githubpackages <- c("nghiavtr/BPSC", "cz-ye/DECENT", "mohuangx/SAVER", "statOmics/zingeR")
> ipak(githubpackages, repository = "github")
Downloading GitHub repo nghiavtr/BPSC@master
from URL https://api.github.com/repos/nghiavtr/BPSC/zipball/master
Installing BPSC
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/gcrynen/AppData/Local/Temp/Rtmpg5DfOm/devtools2fe076323993/nghiavtr-BPSC-1fe6f32"  \
  --library="C:/Users/gcrynen/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'BPSC' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package 'BPSC'
    finding HTML links ... done
    BPSC-package                            html  
    BPfam                                   html  
    BPglm                                   html  
    estimateBP                              html  
    estimateBPMatrix                        html  
    getBPMCnull                             html  
    getBPMCnullmatrix                       html  
    getBin                                  html  
    getInitParam                            html  
    getMCpval                               html  
    getTbreak                               html  
    meanBP                                  html  
    pBP                                     html  
    pBPi                                    html  
    rBP                                     html  
    summary.BPglm                           html  
    varBP                                   html  
** building package indices
** installing vignettes
   'BPSC.Rnw' 
Warning in test_latex_pkg("framed", system.file("misc", "framed.sty", package = "knitr")) :
  unable to find LaTeX package 'framed'; will use a copy from knitr
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (BPSC)
In R CMD INSTALL
Downloading GitHub repo cz-ye/DECENT@master
from URL https://api.github.com/repos/cz-ye/DECENT/zipball/master
Installing DECENT
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/gcrynen/AppData/Local/Temp/Rtmpg5DfOm/devtools2fe0112a1c87/cz-ye-DECENT-fb9a045"  \
  --library="C:/Users/gcrynen/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'DECENT' ...
** libs

*** arch - i386
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.4/include" -DNDEBUG  -I"C:/Users/gcrynen/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/gcrynen/Documents/R/win-library/3.4/RcppEigen/include" -I"C:/Users/gcrynen/Documents/R/win-library/3.4/RcppNumerical/include"        -O2 -Wall  -mtune=generic -c LRT_logl.cpp -o LRT_logl.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.4/include" -DNDEBUG  -I"C:/Users/gcrynen/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/gcrynen/Documents/R/win-library/3.4/RcppEigen/include" -I"C:/Users/gcrynen/Documents/R/win-library/3.4/RcppNumerical/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_32/bin/g++ -shared -s -static-libgcc -o DECENT.dll tmp.def LRT_logl.o RcppExports.o -LC:/PROGRA~1/R/R-34~1.4/bin/i386 -lR
installing to C:/Users/gcrynen/Documents/R/win-library/3.4/DECENT/libs/i386

*** arch - x64
C:/RBuildTools/3.4/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.4/include" -DNDEBUG  -I"C:/Users/gcrynen/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/gcrynen/Documents/R/win-library/3.4/RcppEigen/include" -I"C:/Users/gcrynen/Documents/R/win-library/3.4/RcppNumerical/include"        -O2 -Wall  -mtune=generic -c LRT_logl.cpp -o LRT_logl.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.4/include" -DNDEBUG  -I"C:/Users/gcrynen/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/gcrynen/Documents/R/win-library/3.4/RcppEigen/include" -I"C:/Users/gcrynen/Documents/R/win-library/3.4/RcppNumerical/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_64/bin/g++ -shared -s -static-libgcc -o DECENT.dll tmp.def LRT_logl.o RcppExports.o -LC:/PROGRA~1/R/R-34~1.4/bin/x64 -lR
installing to C:/Users/gcrynen/Documents/R/win-library/3.4/DECENT/libs/x64
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package 'DECENT'
    finding HTML links ... done
    Estep2ByGene                            html  
    EstepByGene                             html  
    MstepNB                                 html  
    calc2DOProb                             html  
    calc2NBProb                             html  
    calc2PoisProb                           html  
    calcDOProb                              html  
    calcNBProb                              html  
    dbetabinom2                             html  
    dbinom2                                 html  
    decent                                  html  
    dnbinom2                                html  
    dpois2                                  html  
    fitDE                                   html  
    fitNoDE                                 html  
    getImputed                              html  
    loglI                                   html  
    loglI2                                  html  
    lrTest                                  html  
    sim                                     html  
    zinbGrad                                html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (DECENT)
In R CMD INSTALL
Downloading GitHub repo mohuangx/SAVER@master
from URL https://api.github.com/repos/mohuangx/SAVER/zipball/master
Installing SAVER
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/gcrynen/AppData/Local/Temp/Rtmpg5DfOm/devtools2fe019ed2c37/mohuangx-SAVER-b2e9ff0"  \
  --library="C:/Users/gcrynen/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'SAVER' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package 'SAVER'
    finding HTML links ... done
    SAVER-package                           html  
    calc.maxcor                             html  
    calc.post                               html  
    calc_estimate                           html  
    calc_loglik                             html  
    combine.saver                           html  
    cor_adjust                              html  
    expr.predict                            html  
    linnarsson                              html  
    optimize_variance                       html  
    sample.saver                            html  
    saver                                   html  
    saver_fit                               html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (SAVER)
In R CMD INSTALL
Downloading GitHub repo statOmics/zingeR@master
from URL https://api.github.com/repos/statOmics/zingeR/zipball/master
Installing zingeR
Installing 1 package: DESeq2
Installing package into ‘C:/Users/gcrynen/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://bioconductor.org/packages/3.6/bioc/bin/windows/contrib/3.4/DESeq2_1.18.1.zip'
Content type 'application/zip' length 4542389 bytes (4.3 MB)
downloaded 4.3 MB

package ‘DESeq2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\gcrynen\AppData\Local\Temp\Rtmpg5DfOm\downloaded_packages
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/gcrynen/AppData/Local/Temp/Rtmpg5DfOm/devtools2fe0397630a0/statOmics-zingeR-c789ae5"  \
  --library="C:/Users/gcrynen/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'zingeR' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package 'zingeR'
    finding HTML links ... done
    NBsimSingleCell                         html  
    getDatasetZTNB                          html  
    glmWeightedF                            html  
Rd warning: C:/Users/gcrynen/AppData/Local/Temp/Rtmpg5DfOm/devtools2fe0397630a0/statOmics-zingeR-c789ae5/man/glmWeightedF.Rd:20: missing file link 'glmLRT'
Rd warning: C:/Users/gcrynen/AppData/Local/Temp/Rtmpg5DfOm/devtools2fe0397630a0/statOmics-zingeR-c789ae5/man/glmWeightedF.Rd:37: missing file link 'glmLRT'
    independentFiltering                    html  
Rd warning: C:/Users/gcrynen/AppData/Local/Temp/Rtmpg5DfOm/devtools2fe0397630a0/statOmics-zingeR-c789ae5/man/independentFiltering.Rd:14: missing file link 'glmLRT'
    islamEset                               html  
    zeroWeightsLS                           html  
Rd warning: C:/Users/gcrynen/AppData/Local/Temp/Rtmpg5DfOm/devtools2fe0397630a0/statOmics-zingeR-c789ae5/man/zeroWeightsLS.Rd:23: missing file link 'DESeqDataSet-class'
Rd warning: C:/Users/gcrynen/AppData/Local/Temp/Rtmpg5DfOm/devtools2fe0397630a0/statOmics-zingeR-c789ae5/man/zeroWeightsLS.Rd:25: missing file link 'DESeqDataSet-class'
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (zingeR)
In R CMD INSTALL
> devtools::install_github("bvieth/powsimR", build_vignettes = TRUE, dependencies = FALSE)
Downloading GitHub repo bvieth/powsimR@master
from URL https://api.github.com/repos/bvieth/powsimR/zipball/master
Installing powsimR
Installation failed: SVN does not seem to be installed on your system.

I also used the alternative method but that gives the same results.

thank you very much
gogce

**Comment by bvieth** [comment]
Hello,

thanks for trying out powsimR!
So there appears to be an issue with the subversion (SVN). 
If you successfully installed all dependencies of powsimR (see also [https://github.com/bvieth/powsimR/issues/20#issuecomment-393850730](url)), you can manually install powsimR:

Step 1: Download the source zip from github.
Step 2: Unzip the content.
Step 3: Run the following code (adjust the path as necessary):
`library(devtools);
source <- devtools::source_pkg("E:/temp/powsimR-master");
devtools::install(source);
library(powsimR)`

I hope this helps!

Kind regards
Beate

**Comment by gcrynen** [comment]
hi 
i still get error message. 
> library(devtools); source <- devtools::source_pkg("C:/Users/gcrynen/Documents/powsimR-master"); devtools::install(source); library(powsimR)
Error: 'source_pkg' is not an exported object from 'namespace:devtools'

so I added one more : between devtools and source pkg and i get the SVN error. 
> library(devtools); source <- devtools:::source_pkg("C:/Users/gcrynen/Documents/powsimR-master"); devtools::install(source); library(powsimR)
Installing powsimR
Error: SVN does not seem to be installed on your system.

**Comment by gcrynen** [comment]
Thank you for the advice,  I hate to be the bearer of bad news but that didnt work either, here is the log

> install.packages("C:/Users/gcrynen/Dropbox (Scripps Research)/Downloads/powsimR.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/gcrynen/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package 'powsimR' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Warning: replacing previous import 'DECENT::lrTest' by 'MAST::lrTest' when loading 'powsimR'
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/gcrynen/Documents/R/win-library/3.4/rtracklayer/libs/x64/rtracklayer.dll':
  `maximal number of DLLs reached...
ERROR: lazy loading failed for package 'powsimR'
* removing 'C:/Users/gcrynen/Documents/R/win-library/3.4/powsimR'
In R CMD INSTALL
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" CMD INSTALL -l "C:\Users\gcrynen\Documents\R\win-library\3.4" "C:/Users/gcrynen/DROPBO~1/DOWNLO~1/powsimR.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/gcrynen/DROPBO~1/DOWNLO~1/powsimR.tar.gz’ had non-zero exit status

**Comment by bvieth** [comment]
Hello,

so from your message above I can see that you have reached the maximum number of DLLs. As explained in the README file, you can set this system environmental variable to a higher number:

Starting with R version 3.4.0, one can set the environmental variable 'R_MAX_NUM_DLLS' to a higher number.  I recommend to increase the maximum number of DLLs that can be loaded to at least 500. For that locate the Renviron file: First determine your R_HOME directory (see the output of `R.home(component="home")`), then in there, you will find the Renviron file in etc/ folder.  Open the file with an editor and add the following line: R_MAX_NUM_DLLS=500. Save the changes to the file and restart your R to load the changes.

Kind regards
Beate

**Comment by gcrynen** [comment]
thank you for the quick reply. This helped me through installation  but then when i loaded the package it gave me a similar maximum dll error. I looked at ?Startup file and reading that I created a "Renviron.site" file  with the same line you suggested (R_MAX_NUM_DLLS=500) under the same etc folder (C:\Program Files\R\R-3.4.4\etc)  and it worked! 
thank you very much for all the help.
