### ISSUE TITLE
Issue regarding "hd5" for Seurat

### ISSUE THREAD

**Issue by fly4all** [bvieth/powsimR#25]
I've been getting an error on trying to do install.packages("Seurat")

This is what I got:
Installing package into ‘/home/ahmedmar/Rlibrary/3.4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/src/contrib/Seurat_2.3.4.tar.gz'
Content type 'application/x-gzip' length 861959 bytes (841 KB)

downloaded 841 KB

* installing *source* package ‘Seurat’ ...
** package ‘Seurat’ successfully unpacked and MD5 sums checked
** libs
g++ -std=gnu++11 -I/sw/arcts/centos7/R/3.4.1/lib64/R/include -DNDEBUG  -I"/home/ahmedmar/Rlibrary/3.4.1/Rcpp/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppEigen/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppProgress/include" -I/usr/local/include   -fpic  -g -O2 -c ModularityOptimizer.cpp -o ModularityOptimizer.o
g++ -std=gnu++11 -I/sw/arcts/centos7/R/3.4.1/lib64/R/include -DNDEBUG  -I"/home/ahmedmar/Rlibrary/3.4.1/Rcpp/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppEigen/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppProgress/include" -I/usr/local/include   -fpic  -g -O2 -c RModularityOptimizer.cpp -o RModularityOptimizer.o
g++ -std=gnu++11 -I/sw/arcts/centos7/R/3.4.1/lib64/R/include -DNDEBUG  -I"/home/ahmedmar/Rlibrary/3.4.1/Rcpp/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppEigen/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppProgress/include" -I/usr/local/include   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I/sw/arcts/centos7/R/3.4.1/lib64/R/include -DNDEBUG  -I"/home/ahmedmar/Rlibrary/3.4.1/Rcpp/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppEigen/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppProgress/include" -I/usr/local/include   -fpic  -g -O2 -c data_manipulation.cpp -o data_manipulation.o
g++ -std=gnu++11 -I/sw/arcts/centos7/R/3.4.1/lib64/R/include -DNDEBUG  -I"/home/ahmedmar/Rlibrary/3.4.1/Rcpp/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppEigen/include" -I"/home/ahmedmar/Rlibrary/3.4.1/RcppProgress/include" -I/usr/local/include   -fpic  -g -O2 -c snn.cpp -o snn.o
g++ -std=gnu++11 -shared -L/sw/arcts/centos7/R/3.4.1/lib64/R/lib -L/usr/local/lib64 -o Seurat.so ModularityOptimizer.o RModularityOptimizer.o RcppExports.o data_manipulation.o snn.o -L/sw/arcts/centos7/R/3.4.1/lib64/R/lib -lR
installing to /home/ahmedmar/Rlibrary/3.4.1/Seurat/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/ahmedmar/Rlibrary/3.4.1/hdf5r/libs/hdf5r.so':
  /home/ahmedmar/Rlibrary/3.4.1/hdf5r/libs/hdf5r.so: invalid ELF header
ERROR: lazy loading failed for package ‘Seurat’
* removing ‘/home/ahmedmar/Rlibrary/3.4.1/Seurat’

The downloaded source packages are in
	‘/tmp/RtmpXkgxMp/downloaded_packages’
Warning message:
In install.packages("Seurat", repos = "https://cran.r-project.org") :
  installation of package ‘Seurat’ had non-zero exit status

**Comment by bvieth** [comment]
Hello,

thanks for trying out powsimR!

So, considering the error message, a dependency of Seurat cannot be installed, namely hdf5r. I would try to install that first and check what other dependencies outside of R might cause the problem.

For example, if i try to install on a newly set-up unix machine, i get the following message while trying to install hdf5r:

configure: error: hdf5 does not seem to be installed on your platform.
  Please install the hdf5 library.
  The required HDF5 library files can be installed as follows:
      - Debian-based (e.g. Debian >= 8.0, Ubuntu >= 15.04): 'sudo apt-get install libhdf5-dev'
        - Old Debian-based (e.g Debian < 8.0, Ubuntu < 15.04): Install from source (see INSTALL)
        - OS X using Homebrew: 'brew install homebrew/science/hdf5'
        - RPM-based (e.g Fedora): 'sudo yum install hdf5-devel'
ERROR: configuration failed for package ‘hdf5r’

Furthermore you can try to install Seurat manually by downloading the compiled tar.gz file from CRAN.

Feel free to contact me again if you encounter any other issue!

Kind regards
Beate

**Comment by bvieth** [comment]
Hello,

I hope that my previous message solved your issue. 
I will close the issue for now but feel free to contact me again if you need further assistance.

Kind regards
Beate
