### ISSUE TITLE
could not find function "Githubpkg"

### ISSUE THREAD

**Issue by virenp** [bvieth/powsimR#26]
Hello. I am trying to install in R/3.4.3. I think I have all dependencies resolved, but now get the subject error message:

% R

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(devtools)
> devtools::install_github("bvieth/powsimR", build_vignettes = TRUE, dependencies = FALSE)
Downloading GitHub repo bvieth/powsimR@master
from URL https://api.github.com/repos/bvieth/powsimR/zipball/master
Installing powsimR
'/sw/Pkgs/R/3.4.3/lib64/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build  \
  '/tmp/Rtmp9JIlHZ/devtools5c872efbd8d0/bvieth-powsimR-f3e43ef'  \
  --no-resave-data --no-manual

* checking for file ‘/tmp/Rtmp9JIlHZ/devtools5c872efbd8d0/bvieth-powsimR-f3e43ef/DESCRIPTION’ ... OK
* preparing ‘powsimR’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
Quitting from lines 2-23 (powsimR.Rmd)
Error: processing vignette 'powsimR.Rmd' failed with diagnostics:
could not find function "Githubpkg"
Execution halted
Installation failed: Command failed (1)

Not sure what to do here. Any thoughts?

**Comment by virenp** [comment]
Sorry, didn't see the warning about Pandoc... installed Pandoc and all is well. Thanks.

**Comment by bvieth** [comment]
Great that it works for you!
I will close the issue for now but feel free to contact me again if you need further assistance.

Kind regards
Beate
