### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by DanUNC** [bvieth/powsimR#29]
Hello, I am working on an install and encountering the following error:

devtools::install_github("bvieth/powsimR")

Downloading GitHub repo bvieth/powsimR@master
from URL https://api.github.com/repos/bvieth/powsimR/zipball/master
Installing powsimR
svn: E170013: Unable to connect to a repository at URL 'https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/AnnotationDbi'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted
Installation failed: There was a problem retrieving the current SVN revision
Warning message:
running command ''/usr/bin/svn' info --xml --username readonly --password readonly https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/AnnotationDbi' had status 1

**Comment by bvieth** [comment]
Hello,

I also have encountered this issue with Bioconductor repositories.Sometimes this actually occurs when they are updating their repos and it is then unavailable, i.e. as the message said you are unable to connect.
A quick fix would be to manually install the dependencies as described in the installation guide: https://bvieth.github.io/powsimR/#installation-guide.

Kind regards
Beate
