### ISSUE TITLE
powsimR installation forces BASiCS download

### ISSUE THREAD

**Issue by haniap** [bvieth/powsimR#3]
Hello again,

I am just trying to install powsimR onto my work computer and although I already have BASiCS installed, the installation of powsimR overrides it and re-installs it again. Is there a way around this as it is creating a  conflict with the various requirements of R versions? I attach the error below.
With many thanks,
Hania

> devtools::install_github("bvieth/powsimR", build_vignettes = FALSE)
Downloading GitHub repo bvieth/powsimR@master
from URL https://api.github.com/repos/bvieth/powsimR/zipball/master
Installing powsimR
Skipping install for github remote, the SHA1 (d5d27442) has not changed since last install.
  Use `force = TRUE` to force installation
Skipping install for github remote, the SHA1 (1fe6f32d) has not changed since last install.
  Use `force = TRUE` to force installation
Downloading GitHub repo catavallejos/BASiCS@master
from URL https://api.github.com/repos/catavallejos/BASiCS/zipball/master
Installing BASiCS
Skipping 1 unavailable package: SingleCellExperiment
Skipping 1 package ahead of CRAN: AnnotationDbi
Installing 1 package: XML
trying URL 'https://cran.rstudio.com/src/contrib/XML_3.98-1.9.tar.gz'
Content type 'application/x-gzip' length 1599437 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

* installing *source* package ‘XML’ ...
** package ‘XML’ successfully unpacked and MD5 sums checked
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for sed... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking for xml2-config... /ifs/devel/haniap/py35-v1/conda/envs/py35-v1/bin/xml2-config
USE_XML2 = yes
SED_EXTENDED_ARG: -E
Minor 9, Patch 4 for 2.9.4
Located parser file -I/ifs/devel/haniap/py35-v1/conda/envs/py35-v1/include/libxml2 -I/ifs/devel/haniap/py35-v1/conda/envs/py35-v1/include/parser.h
Checking for 1.8:  -I/ifs/devel/haniap/py35-v1/conda/envs/py35-v1/include/libxml2 -I/ifs/devel/haniap/py35-v1/conda/envs/py35-v1/include
Using libxml2.*
checking for gzopen in -lz... yes
checking for xmlParseFile in -lxml2... yes
You are trying to use a version 2.* edition of libxml
but an incompatible library. The header files and library seem to be
mismatched. If you have specified LIBXML_INCDIR, make certain to also
specify an appropriate LIBXML_LIBDIR if the libxml2 library is not in the default
directories.
ERROR: configuration failed for package ‘XML’
* removing ‘/ifs/devel/haniap/py35-v1/conda/envs/py35-v1/lib/R/library/XML’
* restoring previous ‘/ifs/devel/haniap/py35-v1/conda/envs/py35-v1/lib/R/library/XML’

The downloaded source packages are in
	‘/tmp/RtmpakBR97/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
'/ifs/devel/haniap/py35-v1/conda/envs/py35-v1/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpakBR97/devtools12d227c3df23/catavallejos-BASiCS-94c4666'  \
  --library='/ifs/devel/haniap/py35-v1/conda/envs/py35-v1/lib/R/library' --install-tests 

ERROR: this R is version 3.3.1, package 'BASiCS' requires R >= 3.4
Error: Command failed (1)
In addition: Warning message:
In utils::install.packages(pkgs, repos = repos, type = type, dependencies = dependencies,  :
  installation of package ‘XML’ had non-zero exit status

**Comment by bvieth** [comment]
Dear Hania,

thank you for your interest in powsimR.

Apparently the default setting in devtools' install_github is to install all packages listed in the dependencies. To block this unnecessary reinstallation, invoke powsimR's installation with the following command (see also the updated README):

devtools::install_github('bvieth/powsimR', build_vignettes = TRUE, dependencies=FALSE)

I hope this helps!

Best, Beate

**Comment by haniap** [comment]
Perfect - thanks Beate!
