### ISSUE TITLE
could not find function ".bulk.NB.RNAseq_counts"

### ISSUE THREAD

**Issue by DavidKLim** [bvieth/powsimR#37]
Hi. I am trying out the package to simulate some data, and I was able to estimate parameters fine according to pre-normalized data I have "norm_y". However, it seems like the "simulateCounts()" function is giving me the following error:

`Error in .bulk.NB.RNAseq_counts(sim.options = simOptions, phenotype = phenotype,  : 
  could not find function ".bulk.NB.RNAseq_counts"`

I basically followed the manual line by line, and i'm wondering if this function has been deleted from this package? Please advise. Thank you! Below is what I ran:

`estparam <- estimateParam(countData = norm_y, Distribution = 'NB', Protocol = 'Read', RNAseq = 'bulk', Normalisation = 'none')`

`p.foo <- function(x) mvtnorm::rmvnorm(x, mean=c(4,2,1),
                                      sigma = matrix(c(4,2,2,2,3,2, 2, 2, 5), ncol=3))`

`b.foo <- function(x) rnorm(x, mean=0, sd=1.5)`

`sim.dat=simulateCounts(n=c(100,110,90), Thinning = NULL,
                       ngenes=10000,
               p.DE=0.05, pLFC=p.foo,
               p.B=0.1, bLFC=b.foo, bPattern="uncorrelated",
               p.M=NULL, mLFC=NULL,
               params=estparam, LibSize='equal',
               spikeIns = FALSE, spike = NULL, thinSpike = FALSE,
               ActualMeans=FALSE, FillUp=FALSE,
               sim.seed=3, verbose=TRUE)`

**Comment by bvieth** [comment]
Dear Davind,

I am sorry for the inconvenience. While changing a lot for single cell power analysis in powsimR, I forgot to  keeop track of the bulk options. In the new version (1.2.0), this should be resolved.

Kind regards
Beate
