### ISSUE TITLE
vignette powsimR  version 1.1.5

### ISSUE THREAD

**Issue by EugeMiVo** [bvieth/powsimR#38]
Hello,
Would it possible to have access to the new version of the vignette for powsimR 1.1.5
in your Github Page of powsimR or as an html  file? Thank you.

**Comment by bvieth** [comment]
Hello,

my apologies, there should be one in the [vignettes folder](https://github.com/bvieth/powsimR/blob/master/vignettes/powsimR.html).

Kind regards
Beate
