### ISSUE TITLE
Issue with plotParam function

### ISSUE THREAD

**Issue by doliv071** [bvieth/powsimR#4]
Hi Beate,

Really like the idea behind your program.

I have the current error message when running a bulk RNA-seq dataset

```
> simR.test <- estimateParam(countData = counts, Distribution = "NB", RNAseq = "bulk", normalisation = "TMM")
> plotParam(simR.test)
Error in ylim(c(0, 1)) : could not find function "ylim"
```

In addition when I run the example code from the vignette I don't get an error but I also do not get a plot.

Thanks,
-Dave

**Comment by bvieth** [comment]
Hello Dave,

thank you for trying out powsimR! I am sorry for the bug, I forgot to reference ggplot2 in the function correctly. I have released a new version fixing the error.

Kind regards
Beate
