### ISSUE TITLE
Inconsistent arguments to functions

### ISSUE THREAD

**Issue by csoneson** [bvieth/powsimR#40]
Might be related to #35 

The example at https://github.com/bvieth/powsimR/blob/62acf471ff202a0710632ebcc5ee709e87cb9254/R/Evaluate.R#L43-L53 doesn't run (with version 1.1.5), since the `evaluateDist` function does not provide a `readData` argument to `.run.checkup`. There are additional arguments that are not consistently added across the functions, e.g. `Protocol`, `GeneFilter`, `SampleFilter`.

**Comment by bvieth** [comment]
Dear Charlotte,

thank you for pointing out these bugs. While changing estimation functions, I forgot to drag those changes along for evaluateDist(). In the new version (1.2.0) this should be solved.

I will close this issue now, but if there are any further issues, feel free to reopen / message again.

Kind regards
Beate
