### ISSUE TITLE
installing powsimR directly using a conda command

### ISSUE THREAD

**Issue by eboamah** [bvieth/powsimR#41]
Hi All- Relatively new to this conda envs. Can you please share the command to install directly from my MAC terminal. Thx

**Comment by bvieth** [comment]
Hello,

unfortunately I have no direct experience with those environments. I hope this site is helpful:
https://docs.anaconda.com/anaconda/user-guide/tasks/using-r-language/

So apparently, once you have downloaded powsimR as a bundled tar you can install it within anaconda.

Kind regards
Beate
