### ISSUE TITLE
Installation issues -- non-R dependencies

### ISSUE THREAD

**Issue by ekernf01** [bvieth/powsimR#43]
I really wanted to try this package because it looks excellent, but the installation was difficult. Here's what I did to get it to work, and maybe this will help others. 

- Ensure libxml2 v2.9.1, geos 3.7.1, gcc 8.1.0, and gsl 2.4 are on the PATH
- Ignore the errors about RcppParallel. They can lead to difficult issues such as https://github.com/RcppCore/RcppParallel/issues/99 , and apparently it's not actually necessary, because my installation has now nominally worked without it.

Alternatively, would you consider either publishing a Docker or Singularity image for this package, or making more of the dependencies optional? Those would be easier and more reliable than having each user navigate the process separately.

**Comment by bvieth** [comment]
Hello,

thank you for pointing this out for fellow users. 
We are working on a 'light' version to ease installation.

Kind regards
Beate
