### ISSUE TITLE
Which distributions are considered nested in `evaluateDist`? 

### ISSUE THREAD

**Issue by ekernf01** [bvieth/powsimR#45]
In `evaluateDist`, you use a likelihood ratio test when models are nested and a Vuong test otherwise. Which models do you consider to be nested, and for nested models, how do you determine the distribution of the likelihood ratio under the null? 

From a newcomer's perspective, the statistics seem quite tricky. Reading some work by Paul Wilson (links below), it seems that the Poisson and ZIP are "nested" in the sense that the ZIP family includes the Poisson as a special case, but Wilks' Theorem does not apply because the special case happens when the zero-inflation parameter is at the boundary of the parameter space. Unfortunately, this somewhat technical detail really distorts the upper quantiles in Wilson's brief simulation study. There is a convenient workaround where the ZIP model family is expanded to include zero-deflated models too, but I don't know if this has been implemented here or not.

https://stats.stackexchange.com/questions/182020/zero-inflated-poisson-regression-vuong-test-raw-aic-or-bic-corrected-results
https://wlv.openrepository.com/bitstream/handle/2436/622610/Vuong1.pdf?sequence=2

**Comment by bvieth** [comment]
Hello,

I consider the Poisson and Zero-Inflated Poisson Distribution OR the Negative Binomial and Zero-Inflated Negative Binomial to be non-nested and therefore use the Vuong Test to compare the distributional model fits. In addition, I consider the Negative Binomial and Poisson distribution to be nested and thus use the likelihood ratio test to compare the distributional model fits. There is no model fit comparison of Negative Binomial with Zero-Inflated Poisson or Poisson with Zero-Inflated Negative Binomial.

You can find more information concerning evaluation metrics and comparisons in the supplements of the original [powsimR publication](http://dx.doi.org/10.1093/bioinformatics/btx435).

I hope I was able to answer your questions.

Kind regards
Beate

**Comment by concatenize** [comment]
Yes, you did! Thank you!

**Comment by ekernf01** [comment]
Yes, you did! Thank you!
