### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by WXNCjlopez** [bvieth/powsimR#47]
Hi, the Bioconductor package "DEDS" is required, but as mentioned in 

https://bioconductor.org/packages/release/bioc/html/DEDS.html

the package is deprecated. Is there anything I can if I am using R version 4.0? Thank you.

**Comment by newbi-pvh** [comment]
I am experiencing the same problem. I am holding off installing powsimR until I can resolve this issue.

**Comment by cellsera** [comment]
Same deal; I am unable to install powsimR due to the unavailability of DEDS.

**Comment by newbi-pvh** [comment]
I ran thru a couple rounds of updating other dependencies and biocparalell.  DEDS finally installed but now another issue when installing powsimr. 

Good luck!
Pam

**Comment by bvieth** [comment]
Hello,

I am sorry that you have encountered this issue. I have updated powsimR to be compatible with the newest Bioconductor release (MAST had some name changes of functions and DEDS is deprecated). 
I hope you will give it another go.

Feel free to contact me again.

Best
Beate

**Comment by newbi-pvh** [comment]
Wow! thank you so much for your response. I will give it another try.

Best Regards,

Pam

**Comment by WXNCjlopez** [comment]
Hi Beate, 
I got it running, thank you for your prompt response. 
Jose.
