### ISSUE TITLE
Issue with PowerSimR installation

### ISSUE THREAD

**Issue by Arinze-BioX** [bvieth/powsimR#49]
Hello, I tried installing PowerSimR using instructions present at https://github.com/bvieth/powsimR but ran into the following error messages:
* installing *source* package 'powsimR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import 'DECENT::lrTest' by 'MAST::lrTest' when loading 'powsimR'
Error: object 'zlm.SingleCellAssay' is not exported by 'namespace:MAST'
Execution halted
ERROR: lazy loading failed for package 'powsimR'
* removing 'C:/Users/folder/Documents/R/win-library/4.0/powsimR'
Error: Failed to install 'powsimR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Public/TMP/RtmpoN0gRY/file3350321f5e53/powsimR_1.2.1.tar.gz’ had non-zero exit status

**Comment by bvieth** [comment]
Hello,

I am sorry that you have encountered this issue. I have updated powsimR to be compatible with the newest Bioconductor release (MAST had some name changes of functions and DEDS is deprecated). 
I hope you will give it another go.

Feel free to contact me again.

Best
Beate
