### ISSUE TITLE
Error : object ‘counts’ is not exported by 'namespace:scater'

### ISSUE THREAD

**Issue by ttriche** [bvieth/powsimR#5]
With both the release and devel versions of 'scater', it appears that powsimR cannot run.  It turns out that scater imports "counts" from BiocGenerics, and thus namespacing it may be breaking things.  See PR.

**Comment by bvieth** [comment]
Dear Tim, 
thank you for pointing this out! I pushed a new version with the suggested fix.

Kind regards
Beate
