### ISSUE TITLE
Can't install in R v4.01

### ISSUE THREAD

**Issue by mizuwatershui** [bvieth/powsimR#50]
Hi, 

I am trying to install the powsimR in R 4.01.
When I run this script: 
biocpackages <- c("bayNorm", "baySeq", "BiocGenerics", "BiocParallel", "DEDS",
        "DESeq2", "EBSeq", "edgeR", "IHW", "iCOBRA",
                  "limma", "Linnorm", "MAST", "monocle", "NOISeq", "qvalue", "ROTS", "RUVSeq", 
                  "S4Vectors", "scater", "scDD", "scde", "scone", "scran", "SCnorm", 
                  "SingleCellExperiment", "SummarizedExperiment", "zinbwave")
ipak(biocpackages, repository='Bioconductor')

I can't install the DEDS package, so I have tried to install it separately by the command: BiocManager::install("DEDS")  
however, it still doesn't work (my bioconductor version is 3.11), get the warning message:

Warning message:
package ‘DEDS’ is not available (for R version 4.0.1) 

How should I trouble shoot it?

Thank you very much!!

Shui

**Comment by bvieth** [comment]
Dear Shui,

I am sorry that you have encountered this issue. I have updated powsimR to be compatible with the newest Bioconductor release (DEDS is officially deprecated). 
I hope you will give it another go.

Feel free to contact me again.

Best
Beate
