### ISSUE TITLE
FDR

### ISSUE THREAD

**Issue by gcrynen** [bvieth/powsimR#54]
I am having an issue with marginal FDR , they are very high, I ran several of the files and I keep getting 95% FDR (nominal 10%)  and sensible TPRs.
I ran the examples several times, restarted R and ran it but results dont change, FDR is very high unlike the example results.
thank you.

**Comment by bvieth** [comment]
Hi,

I am sorry to hear that you encounter this issue. I will have a look into it. In the meantime you could try an earlier version.

Best
Beate
