### ISSUE TITLE
Package installation failed

### ISSUE THREAD

**Issue by rjb67** [bvieth/powsimR#55]
I'm working on trying to this package to try it out and keep running into issues. I run the following code after installing the dependencies as suggested in the installation guide:

`devtools::install_github("bvieth/powsimR", build_vignettes = TRUE, dependencies = FALSE)`

Doing this, I get the following output:

`✓  checking for file ‘/private/var/folders/jb/kvywbk4j6xg_c0h748ttbklh0000gq/T/RtmpfwkzCi/remotes1412126554b05/bvieth-powsimR-49fd951/DESCRIPTION’ ...
─  preparing ‘powsimR’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package ‘powsimR’ ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   Warning: replacing previous import ‘DECENT::lrTest’ by ‘MAST::lrTest’ when loading ‘powsimR’
   Warning in system2(command = python, args = shQuote(config_script), stdout = TRUE,  :
     running command ''/usr/local/bin/python' '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/reticulate/config/config.py' 2>/dev/null' had status 126
   Error: .onLoad failed in loadNamespace() for 'Rmagic', details:
     call: python_config(python_version, required_module, python_versions)
     error: Error 126 occurred running /usr/local/bin/python 
   Execution halted
   ERROR: lazy loading failed for package ‘powsimR’
─  removing ‘/private/var/folders/jb/kvywbk4j6xg_c0h748ttbklh0000gq/T/RtmpaT9cAI/Rinst1415b2778158f/powsimR’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'powsimR' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Warning in system2(command = python, args = shQuote(config_script), stdout = TRUE,  :
E>   running command ''/usr/local/bin/python' '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/reticulate/config/config.py' 2>/dev/null' had status 126
E> Error: .onLoad failed in loadNamespace() for 'Rmagic', details:
E>   call: python_config(python_version, required_module, python_versions)
E>   error: Error 126 occurred running /usr/local/bin/python 
E> Execution halted
E> ERROR: lazy loading failed for package ‘powsimR’
E> * removing ‘/private/var/folders/jb/kvywbk4j6xg_c0h748ttbklh0000gq/T/RtmpaT9cAI/Rinst1415b2778158f/powsimR’
E>       -----------------------------------
E> ERROR: package installation failed`

Here is my sessionInfo:

`R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    usethis_2.0.1     devtools_2.3.2    pkgload_1.2.0    
 [6] R6_2.5.0          rlang_0.4.10      fastmap_1.1.0     tools_4.0.3       pkgbuild_1.2.0   
[11] sessioninfo_1.1.1 cli_2.3.1         withr_2.4.1       ellipsis_0.3.1    remotes_2.2.0    
[16] assertthat_0.2.1  rprojroot_2.0.2   lifecycle_1.0.0   crayon_1.4.1      processx_3.4.5   
[21] purrr_0.3.4       callr_3.5.1       fs_1.5.0          ps_1.6.0          curl_4.3         
[26] testthat_3.0.2    memoise_2.0.0     glue_1.4.2        cachem_1.0.4      compiler_4.0.3   
[31] desc_1.3.0        prettyunits_1.1.1`

**Comment by bvieth** [comment]
Hey,

I have removed the Rmagic dependency in the powsimR version on the lite branch. You can install it using:
`remotes::install_github("bvieth/powsimR", ref = "lite", dependencies = TRUE, upgrade = "ask")`

HTH
Beate
