### ISSUE TITLE
Installation Failed R v. 4.1.0

### ISSUE THREAD

**Issue by Yashrajsinh-Jadeja** [bvieth/powsimR#57]
I was trying to install on version 4.0.x earlier but it was giving me errors (a dependency named 'scuttle' and some others weren't available for R version 4.0.x). So I decided to completely wipe my R and reinstalled it in case there was an issue buried somewhere in the packages (conflicts and such). This time around I tried using R version 4.1.0 and now attempting to install the package gives me this error.

`> devtools::install_github("bvieth/powsimR", build_vignettes = TRUE, dependencies = FALSE)
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo bvieth/powsimR@HEAD
√  checking for file 'C:\Users\YJ\AppData\Local\Temp\RtmpCENTeS\remotes44546d006755\bvieth-powsimR-49fd951/DESCRIPTION' ... 
-  preparing 'powsimR': (1.6s)
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
         -----------------------------------
-  installing *source* package 'powsimR' ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   Warning: replacing previous import 'DECENT::lrTest' by 'MAST::lrTest' when loading 'powsimR'
   Error: object 'computeSpikeFactors' is not exported by 'namespace:scran'
   Execution halted
   ERROR: lazy loading failed for package 'powsimR'
-  removing 'C:/Users/YJ/AppData/Local/Temp/RtmpaGe8Oc/Rinst3f7069b4535/powsimR'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'powsimR' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> *** moving datasets to lazyload DB
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Warning: replacing previous import 'DECENT::lrTest' by 'MAST::lrTest' when loading 'powsimR'
E> Error: object 'computeSpikeFactors' is not exported by 'namespace:scran'
E> Execution halted
E> ERROR: lazy loading failed for package 'powsimR'
E> * removing 'C:/Users/YJ/AppData/Local/Temp/RtmpaGe8Oc/Rinst3f7069b4535/powsimR'
E>       -----------------------------------
E> ERROR: package installation failed`

This is my session information.

`> session_info()
- Session info ----------------------------------------------------------------------
 setting  value                       
 version  R version 4.1.0 (2021-05-18)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2021-06-13                  

- Packages --------------------------------------------------------------------------
 package              * version  date       lib source                       
 abind                  1.4-5    2016-07-21 [1] CRAN (R 4.1.0)               
 assertthat             0.2.1    2019-03-21 [1] CRAN (R 4.1.0)               
 Biobase                2.52.0   2021-05-19 [1] Bioconductor                 
 BiocGenerics           0.38.0   2021-05-19 [1] Bioconductor                 
 BiocManager            1.30.15  2021-05-11 [1] CRAN (R 4.1.0)               
 bitops                 1.0-7    2021-04-24 [1] CRAN (R 4.1.0)               
 cachem                 1.0.5    2021-05-15 [1] CRAN (R 4.1.0)               
 callr                  3.7.0    2021-04-20 [1] CRAN (R 4.1.0)               
 cli                    2.5.0    2021-04-26 [1] CRAN (R 4.1.0)               
 codetools              0.2-18   2020-11-04 [2] CRAN (R 4.1.0)               
 colorspace             2.0-1    2021-05-04 [1] CRAN (R 4.1.0)               
 crayon                 1.4.1    2021-02-08 [1] CRAN (R 4.1.0)               
 curl                   4.3.1    2021-04-30 [1] CRAN (R 4.1.0)               
 data.table             1.14.0   2021-02-21 [1] CRAN (R 4.1.0)               
 DBI                    1.1.1    2021-01-15 [1] CRAN (R 4.1.0)               
 DECENT                 1.1.0    2021-06-13 [1] Github (cz-ye/DECENT@c441cdf)
 DelayedArray           0.18.0   2021-05-19 [1] Bioconductor                 
 desc                   1.3.0    2021-03-05 [1] CRAN (R 4.1.0)               
 devtools             * 2.4.2    2021-06-07 [1] CRAN (R 4.1.0)               
 doParallel             1.0.16   2020-10-16 [1] CRAN (R 4.1.0)               
 dplyr                  1.0.6    2021-05-05 [1] CRAN (R 4.1.0)               
 edgeR                  3.34.0   2021-05-19 [1] Bioconductor                 
 ellipsis               0.3.2    2021-04-29 [1] CRAN (R 4.1.0)               
 fansi                  0.5.0    2021-05-25 [1] CRAN (R 4.1.0)               
 fastmap                1.1.0    2021-01-25 [1] CRAN (R 4.1.0)               
 foreach                1.5.1    2020-10-15 [1] CRAN (R 4.1.0)               
 fs                     1.5.0    2020-07-31 [1] CRAN (R 4.1.0)               
 generics               0.1.0    2020-10-31 [1] CRAN (R 4.1.0)               
 GenomeInfoDb           1.28.0   2021-05-19 [1] Bioconductor                 
 GenomeInfoDbData       1.2.6    2021-06-13 [1] Bioconductor                 
 GenomicRanges          1.44.0   2021-05-19 [1] Bioconductor                 
 ggplot2                3.3.3    2020-12-30 [1] CRAN (R 4.1.0)               
 glue                   1.4.2    2020-08-27 [1] CRAN (R 4.1.0)               
 gtable                 0.3.0    2019-03-25 [1] CRAN (R 4.1.0)               
 IRanges                2.26.0   2021-05-19 [1] Bioconductor                 
 iterators              1.0.13   2020-10-15 [1] CRAN (R 4.1.0)               
 lattice                0.20-44  2021-05-02 [2] CRAN (R 4.1.0)               
 lifecycle              1.0.0    2021-02-15 [1] CRAN (R 4.1.0)               
 limma                  3.48.0   2021-05-19 [1] Bioconductor                 
 locfit                 1.5-9.4  2020-03-25 [1] CRAN (R 4.1.0)               
 magrittr               2.0.1    2020-11-17 [1] CRAN (R 4.1.0)               
 MASS                   7.3-54   2021-05-03 [2] CRAN (R 4.1.0)               
 MAST                   1.18.0   2021-05-19 [1] Bioconductor                 
 Matrix                 1.3-4    2021-06-01 [2] CRAN (R 4.1.0)               
 MatrixGenerics         1.4.0    2021-05-19 [1] Bioconductor                 
 matrixStats            0.59.0   2021-06-01 [1] CRAN (R 4.1.0)               
 memoise                2.0.0    2021-01-26 [1] CRAN (R 4.1.0)               
 munsell                0.5.0    2018-06-12 [1] CRAN (R 4.1.0)               
 pillar                 1.6.1    2021-05-16 [1] CRAN (R 4.1.0)               
 pkgbuild               1.2.0    2020-12-15 [1] CRAN (R 4.1.0)               
 pkgconfig              2.0.3    2019-09-22 [1] CRAN (R 4.1.0)               
 pkgload                1.2.1    2021-04-06 [1] CRAN (R 4.1.0)               
 plyr                   1.8.6    2020-03-03 [1] CRAN (R 4.1.0)               
 prettyunits            1.1.1    2020-01-24 [1] CRAN (R 4.1.0)               
 processx               3.5.2    2021-04-30 [1] CRAN (R 4.1.0)               
 ps                     1.6.0    2021-02-28 [1] CRAN (R 4.1.0)               
 purrr                  0.3.4    2020-04-17 [1] CRAN (R 4.1.0)               
 R6                     2.5.0    2020-10-28 [1] CRAN (R 4.1.0)               
 Rcpp                   1.0.6    2021-01-15 [1] CRAN (R 4.1.0)               
 RCurl                  1.98-1.3 2021-03-16 [1] CRAN (R 4.1.0)               
 remotes                2.4.0    2021-06-02 [1] CRAN (R 4.1.0)               
 reshape2               1.4.4    2020-04-09 [1] CRAN (R 4.1.0)               
 rlang                  0.4.11   2021-04-30 [1] CRAN (R 4.1.0)               
 rprojroot              2.0.2    2020-11-15 [1] CRAN (R 4.1.0)               
 rstudioapi             0.13     2020-11-12 [1] CRAN (R 4.1.0)               
 S4Vectors              0.30.0   2021-05-19 [1] Bioconductor                 
 scales                 1.1.1    2020-05-11 [1] CRAN (R 4.1.0)               
 sessioninfo            1.1.1    2018-11-05 [1] CRAN (R 4.1.0)               
 SingleCellExperiment   1.14.1   2021-05-21 [1] Bioconductor                 
 statmod                1.4.36   2021-05-10 [1] CRAN (R 4.1.0)               
 stringi                1.6.2    2021-05-17 [1] CRAN (R 4.1.0)               
 stringr                1.4.0    2019-02-10 [1] CRAN (R 4.1.0)               
 SummarizedExperiment   1.22.0   2021-05-19 [1] Bioconductor                 
 testthat               3.0.2    2021-02-14 [1] CRAN (R 4.1.0)               
 tibble                 3.1.2    2021-05-16 [1] CRAN (R 4.1.0)               
 tidyselect             1.1.1    2021-04-30 [1] CRAN (R 4.1.0)               
 usethis              * 2.0.1    2021-02-10 [1] CRAN (R 4.1.0)               
 utf8                   1.2.1    2021-03-12 [1] CRAN (R 4.1.0)               
 vctrs                  0.3.8    2021-04-29 [1] CRAN (R 4.1.0)               
 VGAM                   1.1-5    2021-01-14 [1] CRAN (R 4.1.0)               
 withr                  2.4.2    2021-04-18 [1] CRAN (R 4.1.0)               
 XVector                0.32.0   2021-05-19 [1] Bioconductor                 
 ZIM                    1.1.0    2018-08-28 [1] CRAN (R 4.1.0)               
 zlibbioc               1.38.0   2021-05-19 [1] Bioconductor                 

[1] C:/Users/YJ/Documents/R/win-library/4.1
[2] C:/Program Files/R/R-4.1.0/library`

Could you please look into this or suggest an alternative for getting around this roadblock? Thank you and I really appreciate all the work that has been put into this. Please let me know if I can provide any more information that would help in replicating the error.

Best,
YJ

**Comment by bvieth** [comment]
Dear YJ,

thanks for pointing this out. Apparently scran renamed its normalisation function. I will have a look into this and adapt it accordingly.

Kind regards
Beate
