### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by ptoru001** [bvieth/powsimR#59]
Warning: replacing previous import ‘DECENT::lrTest’ by ‘MAST::lrTest’ when loading ‘powsimR’
Warning in .recacheSubclasses(def@className, def, env) :
  undefined subclass "numericVector" of class "Mnumeric"; definition not updated
Error: object ‘computeSpikeFactors’ is not exported by 'namespace:scuttle'
Execution halted
ERROR: lazy loading failed for package ‘powsimR’
* removing ‘/blah/gitr/renv/library/R-4.0/x86_64-apple-darwin17.0/powsimR’
Warning message:
In i.p(...) :
  installation of package ‘/blah/blahpowsimR_1.2.3.tar.gz’ had non-zero exit status

**Comment by bvieth** [comment]
Hey,

this weas an issue due to namespace changes in my dependencies, I have changed this in the mos recent release.

HTH
Beate
